# Generated by Django 4.1.7 on 2023-03-28 22:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=250, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Заголовок')),
                ('expiration', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 31, 22, 3, 45, 761620), null=True, verbose_name='Актуален до')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('kind', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=250, verbose_name='Статус приватности')),
            ],
            options={
                'verbose_name_plural': 'Diaries',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Текст')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='diary.diary', verbose_name='Дневник')),
            ],
        ),
    ]
