# Generated by Django 4.1.7 on 2023-03-29 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 1, 13, 43, 29, 372214), null=True, verbose_name='Актуален до'),
        ),
    ]
